### PR TITLE
Initial Kicad baseline front panel files commit

### PR DESCRIPTION
**Pull request by SimonMerrett**
I think this will do for starters for the initial Kicad commit. Please check the CHANGELOG.md and README.md are consistent with Jetperch convention. 

If you could get another JS110 user who is conversant with Kicad to do a sanity check at some point, that would be great. Maybe put a request on the JS forum?

I plan to try adding some choice connectors and getting the resulting front panels fabbed, so I will update if they hit any issues in the real world.

### CODE REVIEW

**Comment by mliberty1** [comment]
I just merged your pull request.  I removed the following backup and cache files from the pull request:

- fp_baseline.bak
- fp_baseline-cache.lib
- fp_baseline.kicad_pcb-bak
- fp-info-cache

and I also modified the .gitignore file to ignore them in the future.  I tried opening the project, schematics, and layout in KiCAD 5.1.4 without these files, and it seems to work.  Let me know if I made a mistake.

Thank you for your time and your contribution @SimonMerrett !

**Comment by SimonMerrett** [comment]
Great, thank you.

The cache.lib is supposed to keep copies of the footprints as used in the pcbnew file, to allow a design to be frozen even if the library footprint is updated (AFAIK). If it works, I'm sure it's fine! 

Kudos for installing Kicad just to check - I bet you're glad there's no licence fee to check your community's contributions! 😂

**Comment by mliberty1** [comment]
I took a look at the fp_baseline-cache.lib file, and it contains the SiCAD_JS110_Joulescope (located in fb_baseline_SYMBOL.lib) and Graphic_Logo_Open_Hardware_Small.  I guess we have a small risk that the OSH logo does not show up in the schematic.  The footprint from "fp_baseline_FOOTPRINT.kicad_mod" appears to be copied verbatim into "fp_baseline.kicad_pcb".  Perhaps this avoids the footprint/library issue?

I definitely like KiCAD, and especially the (idea of) python scripting capabilities.  I have a bunch of Eagle Python scripts to maintain my builds and BOMs, and they are all hacked.  Having real python integration would be very nice.

**Comment by SimonMerrett** [comment]
I can live without the OSH logo - the licence info is the most important part and that's in the text. Not sure if the (unconventional) presence of the footprint file is helping the pcb not to notice the missing cache.lib. I'd tend to leave it out and add it back if someone complains! This pr is definitely closed!

**Pull request merged**
